### PR TITLE
Fix the image width to scale to look nice in mobile

### PR DESCRIPTION
**Pull request by kayvee83**
@nareddyt Please see if this fix is good Issue #15 (mobile screenshot display)

### CODE REVIEW

**Comment by nareddyt** [comment]
Thanks for the fix! I know is only a little bit of code change, but I still need to follow the process and run a jekyll build against your changes. I'll do this in the next few days to ensure your fix works!

**Comment by nareddyt** [comment]
Closes #15

**Comment by nareddyt** [comment]
Thanks for the fix, will merge now! I had a chance to build the changes locally. This is what it looks now now (for reference later):

image

**Comment by kayvee83** [comment]
Thanks

**Pull request merged**
